#pragma once
#include "GameObject.h"
#include "Utils.h"

#define YUMETARODIEEFFECT_ANI_SET		7001

#define YUMETARODIEEFFECT_SPEED			0.075f
#define YUMETARODIEEFFECT_SPEED_225		0.924f
#define YUMETARODIEEFFECT_SPEED_450		0.707f
#define YUMETARODIEEFFECT_SPEED_675		0.383f

#define YUMETARODIEEFFECT_ANI_ACTIVE		0

#define YUMETARODIEEFFECT_BBOX_WIDTH		16
#define YUMETARODIEEFFECT_BBOX_HEIGHT		16

class CYumetaroDieEffect : public CGameObject
{
public:
	CYumetaroDieEffect(int direction) : CGameObject()
	{
		switch (direction)
		{
		case 0:
			vx = 0;
			vy = YUMETARODIEEFFECT_SPEED;
			break;
		case 1:
			vx = YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_675;
			vy = YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_225;
			break;
		case 2:
			vx = YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_450;
			vy = YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_450;
			break;
		case 3:
			vx = YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_225;
			vy = YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_675;
			break;
		case 4:
			vx = YUMETARODIEEFFECT_SPEED;
			vy = 0;
			break;
		case 5:
			vx = YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_225;
			vy = -YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_675;
			break;
		case 6:
			vx = YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_450;
			vy = -YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_450;
			break;
		case 7:
			vx = YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_675;
			vy = -YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_225;
			break;
		case 8:
			vx = 0;
			vy = -YUMETARODIEEFFECT_SPEED;
			break;
		case 9:
			vx = -YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_675;
			vy = -YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_225;
			break;
		case 10:
			vx = -YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_450;
			vy = -YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_450;
			break;
		case 11:
			vx = -YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_225;
			vy = -YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_675;
			break;
		case 12:
			vx = -YUMETARODIEEFFECT_SPEED;
			vy = 0;
			break;
		case 13:
			vx = -YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_225;
			vy = YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_675;
			break;
		case 14:
			vx = -YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_450;
			vy = YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_450;
			break;
		case 15:
			vx = -YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_675;
			vy = YUMETARODIEEFFECT_SPEED * YUMETARODIEEFFECT_SPEED_225;
			break;
		default:
			break;
		}
	}
	~CYumetaroDieEffect() {}
	virtual void Update(DWORD dt, vector<LPGAMEOBJECT>* coObjects);
	virtual void Render();
	void SetState(int state);
	virtual void GetBoundingBox(float& l, float& t, float& r, float& b);
};

